import { execSync } from 'child_process'

var handler = async (m, { conn, text }) => {
  m.react('üöÄ') 
  try {
    // Guardar los cambios locales temporalmente
    execSync('git stash')

    // Actualizar el repositorio
    const stdout = execSync('git pull --rebase' + (m.fromMe && text ? ' ' + text : ''));
    let messager = stdout.toString()

    // Restaurar los cambios locales
    execSync('git stash pop')

    if (messager.includes('‚òòÔ∏è Ya estoy actualizada.')) messager = '‚òòÔ∏è Ya estoy actualizada a la √∫ltima versi√≥n.'
    if (messager.includes('üí´ Actualizando.')) messager = '‚ú®Ô∏è Procesando, espere un momento mientras me actualizo.\n\n' + stdout.toString()

    conn.reply(m.chat, messager, m, rcanal,)

  } catch (error) { 
    try {
      const status = execSync('git status --porcelain')

      if (status.length > 0) {
        const conflictedFiles = status.toString().split('\n')
          .filter(line => line.trim() !== '')
          .map(line => '*‚Üí ' + line.slice(3) + '*')
          .filter(Boolean)

        if (conflictedFiles.length > 0) {
          const errorMessage = `üí≠ Se han hecho cambios locales que entran en conflicto con las actualizaciones del repositorio.\n\n‚ú∞ *ARCHIVOS EN CONFLICTO*\n\n${conflictedFiles.join('\n')}`
          await conn.reply(m.chat, errorMessage, m, rcanal,)
        }
      }
    } catch (error) {
      console.error(error)
      let errorMessage2 = '‚ö†Ô∏è Ocurri√≥ un error inesperado.'
      if (error.message) {
        errorMessage2 += '\n‚ö†Ô∏è Mensaje de error: ' + error.message;
      }
      await conn.reply(m.chat, errorMessage2, m, rcanal,)
    }
  }
}

handler.help = ['update', 'actualizar']
handler.tags = ['owner']
handler.command = ['update', 'actualizar', 'up']
handler.rowner = true

export default handler